services:
  - type: web
    name: uchiha-bot
    env: python
    plan: free
    buildCommand: apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
